### ISSUE TITLE
Invalid amount error message has a misspelt word 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-talk#1241]
### Description
Invalid amount error message has a misspelt word 

### Steps to reproduce

1. Click on Send crypto 
2. Enter an invalid input value
3. Error message has a misspelt word

### Actual Result
![image](https://github.com/brave/brave-talk/assets/17010094/86021713-c773-41df-8f03-11f1c7647b4b)

### Expected Result
![image](https://github.com/brave/brave-talk/assets/17010094/cb509033-4ba7-45b2-930a-b6680005829d)

### Additional Information
cc: @mrose17

**Comment by mrose17** [comment]
@srirambv - this should be fixed on `dev2` ...

**Comment by srirambv** [comment]
Still doesn't look fixed. Says <code>You entered <b>in</b> invalid amount input</code> instead of <code>You entered <b>an</b> invalid input amount</code>
![brave_qYd3Pvx2Gz](https://github.com/brave/brave-talk/assets/17010094/3b362894-d694-4910-bb4d-f77596bd167e)
